### ISSUE TITLE
Request for support for RTL8852AE wifi driver.

### ISSUE THREAD

**Issue by manasbiswal604** [BlissRoms-x86/external_kernel-drivers#10]
would you please add wifi driver support for realtek wifi adapter. I am providing the link of linux drivers for it.

https://github.com/lwfinger/rtw89

**Comment by hmtheboy154** [comment]
Use Zenith build
https://github.com/android-generic/kernel-zenith/blob/6.9/arch/x86/configs/android-x86_64_defconfig#L3532

**Comment by sagarkhatiwada1** [comment]
> Use Zenith build https://github.com/android-generic/kernel-zenith/blob/6.9/arch/x86/configs/android-x86_64_defconfig#L3532

will it work for 8852ax too?
