### ISSUE TITLE
Issue with r8188eu

### ISSUE THREAD

**Issue by nayeemtby** [BlissRoms-x86/external_kernel-drivers#3]
Problem: Pressing the on button in wifi settings automatically turns off after half a second.
Insight: 
in 'lsmod' it shows the driver r8188eu loaded [Pastebin](https://pastebin.com/KuAtdX05)
in 'ifconfig' it shows wlan0, tried 'ifconfig wlan0 up', But no effect [Pastebin](https://pastebin.com/pb79ZfyF)
in 'logcat -d | grep Wifi' [Pastebin](https://pastebin.com/Z6eNDuQF) :

08-26 03:34:24.081  2870  2870 W hwservicemanager: getTransport: Cannot find entry android.hardware.wifi@1.0::IWifi/default in either framework or device manifest.
08-26 03:34:24.081  3237  3326 I WifiNative: Vendor Hal not supported, ignoring createStaIface.
08-26 03:34:24.081  3237  3326 D WificondControl: Setting up interface for client mode
08-26 03:34:24.081  3237  3326 E WificondControl: Could not get IClientInterface instance from wificond
08-26 03:34:24.081  3237  3326 E WifiNative: Failed to setup iface in wificond on Iface:{Name=wlan0,Id=3,Type=STA}

More logs: [Pastebin](https://pastebin.com/gj97NWN2) [Pastebin](https://pastebin.com/bjBZYRAF)

**Comment by nayeemtby** [comment]
BTW, Its a usb wifi adapter.

**Comment by hmtheboy154** [comment]
Go to /system/etc/modules.blacklist and add this line
`blacklist r8188eu`
I guess @electrikjesus  forgot to disable the rtl8188eu inside the kernel

**Comment by nayeemtby** [comment]
I did that, but it loaded some virt_wifi driver instead of my rtl8188eu in the next boot. 
I don't have ethernet, so was hoping to use Wifi.
Would installing kali nethunter help with this issue using iwlist?

**Comment by hmtheboy154** [comment]
If that so, then can you tell me the Bliss version that you are using ?

**Comment by nayeemtby** [comment]
11.13 64bit with gapps

**Comment by hmtheboy154** [comment]
Try FOSS 11.14, I remember that it did include the new 8188eu inside the kernel
Optionally, you can try to update Gearlock and install one of the 3 kernel made by me
https://supreme-gamers.com/r/
(4.19 - 5.4 - 5.10)

**Comment by nayeemtby** [comment]
Used your 5.10, worked like a charm. Even fixed issues I was having with colors in some games. But I still get some fps slowdowns in some games (Not fps drop). But I can work with that.
