### ISSUE TITLE
An error occurred when enabling the acpi_ec module

### ISSUE THREAD

**Issue by ghhccghk** [BlissRoms-x86/external_kernel-drivers#7]
```
:/data/data/com.termux/files/home # modprobe acpi_ec
modprobe: softdep lines in modules.softdep must have at least 4 entries
modprobe: softdep lines in modules.softdep must have at least 4 entries
modprobe: softdep lines in modules.softdep must have at least 4 entries
modprobe: softdep lines in modules.softdep must have at least 4 entries
modprobe: softdep lines in modules.softdep must have at least 4 entries
modprobe: softdep lines in modules.softdep must have at least 4 entries
modprobe: softdep lines in modules.softdep must have at least 4 entries
modprobe: softdep lines in modules.softdep must have at least 4 entries
modprobe: softdep lines in modules.softdep must have at least 4 entries
modprobe: softdep lines in modules.softdep must have at least 4 entries
modprobe: softdep lines in modules.softdep must have at least 4 entries
Loading module /system/lib/modules/5.15.125-GoogleLTS-xanmod1-umbral/extra/src/acpi_ec.ko with args ''
modprobe: Failed to insmod '/system/lib/modules/5.15.125-GoogleLTS-xanmod1-umbral/extra/src/acpi_ec.ko' with args '': Operation not permitted
modprobe: LoadWithAliases was unable to load acpi_ec
modprobe: Failed to load module acpi_ec: Operation not permitted
```

This is the runtime command

**Comment by ghhccghk** [comment]
The system has secured boot turned on

**Comment by hmtheboy154** [comment]
try to turn it off ?

Also I don't think that we ship with acpi_ec module

**Comment by ghhccghk** [comment]
### 

> try to turn it off ?
> 
> Also I don't think that we ship with acpi_ec module

acpi_ec The module is self-integrated because this module is required for fan control.

**Comment by electrikjesus** [comment]
What are it's dependencies then?

**Comment by ghhccghk** [comment]
> > try to turn it off ?
> > Also I don't think that we ship with acpi_ec module
> 
> acpi_ec The module is self-integrated because this module is required for fan control.

The module depends on ec_sys

**Comment by ghhccghk** [comment]
> try to turn it off ?
> 
> Also I don't think that we ship with acpi_ec module

Still can't load after turning off Secure Boot

**Comment by hmtheboy154** [comment]
> > try to turn it off ?
> > Also I don't think that we ship with acpi_ec module
> 
> acpi_ec The module is self-integrated because this module is required for fan control.

But there is no module of it since like...... kernel 2.6
And the only way to build it is to build something like this
https://github.com/musikid/acpi_ec

Are you trying to custom build this kernel ?

**Comment by hmtheboy154** [comment]
> /system/lib/modules/5.15.125-GoogleLTS-xanmod1-umbral/extra/src/acpi_ec.ko

`extra/` meaning that you are building an external driver and  you put this driver in  manually

**Comment by ghhccghk** [comment]
> > > try to turn it off ?
> > > Also I don't think that we ship with acpi_ec module
> > 
> > 
> > acpi_ec The module is self-integrated because this module is required for fan control.
> 
> But there is no module of it since like...... kernel 2.6 And the only way to build it is to build something like this https://github.com/musikid/acpi_ec
> 
> Are you trying to custom build this kernel ?

Yes I'm trying to build a custom kernel

**Comment by ghhccghk** [comment]
After cleaning the kernel compilation environment, everything works normally.This is my personal problem, sorry
